lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: The authors of nfcore/funcscan, Barbara Verhaar
  description: Pipeline for screening for antibiotic resistance genes
  force: false
  is_nfcore: true
  name: amrfinderflow
  outdir: .
  version: 1.0.0
